### ISSUE TITLE
How can I control index Programmatically?

### ISSUE THREAD

**Issue by sunjianan9900** [dmt195/tiktok-flutter-plugin#5]
seems like there's no controller

**Comment by dmt195** [comment]
Yes, you're correct. I've never needed that use case so it wasn't ever something I considered implementing. If you're up to creating a PR, I could happily review it. Otherwise, I will look at implementing in the next few weeks/months.
[This](https://api.flutter.dev/flutter/widgets/ScrollController-class.html) may be useful for reference/future use.

**Comment by dmt195** [comment]
As of version 0.2.0, there is now the ability to control the index/page programmatically. Let me know what you think or if there needs to be different methods of control.
